[server]
  debug_trace = false

[bluemix]
  iam_url = "iam_rul"
  iam_client_id = "bx"
  iam_client_secret = "bx"
  iam_api_key = "XXX"
  refresh_token = ""
  containers_api_route = "api_endpoint"
  containers_api_route_private = "private_api_endpoint"

[vpc]
  vpc_enabled = false
  vpc_block_provider_name = "vpc-classic"
  gc_token_exchange_endpoint_url = "token_exchange_url"
  gc_riaas_endpoint_url = "endpoint_url"
  gc_resource_group_id = ""
  gc_api_key = ""
  encryption = true
  vpc_api_timeout = "120s"
  max_retry_attempt  = 10 # 10 times with exponential re-try with max gap max_retry_gap
  max_retry_gap =  120 # 2 minutes
  api_version = "2019-07-02"
  vpc_api_generation = 1

[IKS]
  iks_enabled = false
  iks_block_provider_name = "iks-vpc-classic"
