[server]
  debug_trace = false
[vpc]
  vpc_enabled = true
  g2_token_exchange_endpoint_url = "https://iam.stage1.bluemix.net"
  g2_riaas_endpoint_url = "https://us-south-stage01.iaasdev.cloud.ibm.com/"
  g2_riaas_endpoint_private_url = "https://us-south-stage01.iaasdev.cloud.ibm.com"
  g2_resource_group_id = ""
  g2_api_key = "api-key"
  provider_type = "g2"
  vpc_block_provider_name = "vpc"
  vpc_volume_type="vpc-block"
  encryption = false
  iks_token_exchange_endpoint_private_url = "https://containers.test.cloud.ibm.com"
  containers_api_csrf_token = ""
  max_retry_attempt  = 2 # 10 times with exponential re-try with max gap max_retry_gap
  max_retry_gap =  120 # 2 minutes
  api_version = "2020-07-02"   #"2019-07-02"
  vpc_api_generation = 2
  vpc_api_timeout = "120s"
[IKS]
  iks_enabled = false
  iks_block_provider_name = "iks-vpc-classic"

[API]
  PassthroughSecret = ""
